services:
    web:
        build: .
        depends_on:
            - mongo
        ports:
            - 8081:8081
        volumes:
            - .:/app/
            - /app/node_modules
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ~/mongo:/data/db
